python generate_latent.py \
          --weights_dir /home/zmy/Downloads/OneDrive-2021-03-04 \
          --input_form 'image' \
          --image_data_dir /home/zmy/Datasets/3d-r2n2-datasat/03001627_processed/image/test_sub \
          --voxel_data_dir /home/zmy/Datasets/3d-r2n2-datasat/03001627_processed/voxel/test_sub \
          --save_dir /home/zmy/Downloads/OneDrive-2021-03-04 \
          --save_ori 0   \
          --generate_img 0 \
          --latent_vector_size 128 \
          --dataset 'modelnet' \
